### ISSUE TITLE
Can't use `labels` in multiple `models` files

### ISSUE THREAD

**Issue by dekimir** [chiselstrike/chiselstrike#1201]
When two different `models` files both import `labels` and one uses it, then `chisel apply` fails with this message:
```
Error: parsing endpoint /dev/po

Caused by:
    TypeError: Uncaught SyntaxError: Identifier 'labels' has already been declared
        at file:///dev/po.js?ver=2:5:9
        at async importEndpointImpl (file:///worker.js:39:17)
        at async handleMsg (file:///worker.js:13:17)
```

This is the minimal example that reproduces it:
```bash
$ cat models/person.ts 
import { labels } from "@chiselstrike/api";
export class Person {
  @labels("pii") last_name: string = "";
}
$ cat models/post.ts 
import { labels } from '@chiselstrike/api';
$ cat endpoints/po.ts 
export default async function (req: Request) {}
```

**Comment by espindola** [comment]
mergify got this wrong
