### ISSUE TITLE
Entities are not usable from event handlers

### ISSUE THREAD

**Issue by penberg** [chiselstrike/chiselstrike#1665]
I have an example application where I define an entity in `models`. Using from an endpoint works fine, but when I attempt to use it from an event handler, the following error appears:

```
Unhandled exception: Error: Promise rejected without a handler: Error: unable to construct QueryPlan from an unknown entity name `TopOfBook`
    at file:///worker.js:6:15
    at Object.[Symbol.asyncIterator] (file:///chisel.ts:63:31)
    at AsyncGenerator.next (<anonymous>)
    at Function.findOne (file:///chisel.ts:574:26)
    at Object.book_updates_default [as /dev/book-updates] (file:///dev/events/book-updates:18:31)
    at callEventHandlerImpl (file:///worker.js:194:28)
    at async rollback_on_failure (file:///worker.js:85:16)
    at async handleMsg (file:///worker.js:23:17)
Unhandled exception: Error: Promise rejected without a handler: Error: unable to construct QueryPlan from an unknown entity name `TopOfBook`
    at file:///worker.js:6:15
    at Object.book_updates_default [as /dev/book-updates] (file:///dev/events/book-updates:38:1)
```

**Comment by penberg** [comment]
As @honzasp points out, we need to set the `apiVersion` in `requestContext`:

```patch
diff --git a/api/src/worker.ts b/api/src/worker.ts
index 82a8b681..b720bc92 100644
--- a/api/src/worker.ts
+++ b/api/src/worker.ts
@@ -297,6 +297,8 @@ async function callEventHandlerImpl(
     key: ArrayBuffer,
     value: ArrayBuffer,
 ) {
+    requestContext.apiVersion = apiVersion;
+
     await Deno.core.opAsync("op_chisel_start_event_handler");
 
     await Deno.core.opAsync("op_chisel_create_transaction");
```

However, that doesn't fully fix the issue. Now a `findOne()` call fails with:

```
Unhandled exception: Error: Promise rejected without a handler: Interrupted: operation canceled
    at file:///worker.js:6:15
    at Object.book_updates_default [as /dev/book-updates] (file:///dev/events/book-updates:22:1)
```
