### ISSUE TITLE
Invalid query string in the tutorial

### ISSUE THREAD

**Issue by penberg** [chiselstrike/chiselstrike#1696]
We have the following in the tutorial in https://docs.chiselstrike.com/Intro/first#relationships:

```
curl -g "localhost:8080/dev/comments?.by.age~lt=40&.by.name=John&sort=by.name"
```

but it fails to run as follows:

```
Unhandled exception: Error: Promise rejected without a handler: Error: failed to parse query param '.by.age~lt' with value '40'
    at file:///worker.js:5:11
    at Object.[Symbol.asyncIterator] (file:///chisel.ts:517:27)
    at iter.next (<anonymous>)
    at fetchEntitiesCrud (file:///chisel.ts:522:22)
    at GET (file:///chisel.ts:541:41)
    at Object./dev/comments (file:///chisel.ts:601:16)
    at callHandlerImpl (file:///worker.js:128:41)
    at async rollback_on_failure (file:///worker.js:57:16)
    at async handleMsg (file:///worker.js:16:17)
```

**Comment by penberg** [comment]
I had `create-chiselstrike-app` create a project with old version of ChiselStrike. Works fine with latest.
