### ISSUE TITLE
"digital envelope routines::unsupported" error when building on Fedora 36

### ISSUE THREAD

**Issue by penberg** [chiselstrike/chiselstrike#1866]
I am seeing the following error when building on Fedora 36:

```console
> create-chiselstrike-app@0.14.0-dev.0 build
  > rimraf ./dist && ncc build ./index.ts -o ./dist/

  ncc: Version 0.33.1
  ncc: Compiling file index.js into CJS

  --- stderr
  node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:130:10)
      at hashOf (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1890023)
      at ncc (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1894690)
      at runCmd (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:52268)
      at Object.819 (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48838)
      at __webpack_require__ (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59076)
      at /home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59288
      at /home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59349
      at Object.<anonymous> (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }
  npm ERR! code 1
  npm ERR! path /home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app
  npm ERR! command failed
  npm ERR! command sh -c npm run build

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/penberg/.npm/_logs/2022-10-25T08_04_26_394Z-debug-0.log
  thread 'main' panicked at 'assertion failed: status.unwrap().success()', packages/build.rs:68:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@haaawk already fixed a similar issue in 4a7639c2297fbe49699193383b535585f5d8c9a8 so unsure why it's triggering again. I have Node v16.14.0 that's comes with Fedora 36.

**Comment by haaawk** [comment]
This is actually caused by my change. I added `--openssl-legacy-provider` to `NODE_OPTIONS`.
It's weird that it fails since `openssl_legacy_provider_supported` in my change should have checked whether it's supported or not and act accordingly.

**Comment by haaawk** [comment]
You could try commenting out[ this line](https://github.com/chiselstrike/chiselstrike/commit/4a7639c2297fbe49699193383b535585f5d8c9a8#diff-f43a6bc1c6cf18b75d83d4f63e2e7e4f876a2a4b387192343871609d4e93258cR58) and see if it helps and then checking out why `openssl_legacy_provider_supported` returns `true` when it clearly should return `false`.

**Comment by penberg** [comment]
With this:

```
diff --git a/packages/build.rs b/packages/build.rs
index 8dd10d44..fb48dca8 100644
--- a/packages/build.rs
+++ b/packages/build.rs
@@ -55,7 +55,7 @@ fn run_in(cmd: &str, args: &[&str], dir: PathBuf) {
     assert!(dir.is_dir(), "{:?} is not a directory", dir);
     let mut command = Command::new(cmd);
     if openssl_legacy_provider_supported() {
-        command.env("NODE_OPTIONS", "--openssl-legacy-provider");
+        //command.env("NODE_OPTIONS", "--openssl-legacy-provider");
     };
     let status = command.args(args).current_dir(dir.clone()).status();
     assert!(
@@ -70,7 +70,7 @@ fn run_in(cmd: &str, args: &[&str], dir: PathBuf) {
 
 fn openssl_legacy_provider_supported() -> bool {
     let status = Command::new("node")
-        .env("NODE_OPTIONS", "--openssl-legacy-provider")
+//        .env("NODE_OPTIONS", "--openssl-legacy-provider")
         .arg("-v")
         .status();
     status.is_ok() && status.unwrap().success()
```

build fails with:

```
error: failed to run custom build command for `packages v0.14.0-dev.0 (/home/penberg/src/chiselstrike/chiselstrike/packages)`

Caused by:
  process didn't exit successfully: `/home/penberg/src/chiselstrike/chiselstrike/target/debug/build/packages-3093949915ba5a24/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./chiselstrike-api/package.json
  cargo:rerun-if-changed=./create-chiselstrike-app/index.ts
  cargo:rerun-if-changed=./create-chiselstrike-app/template/Chisel.toml
  cargo:rerun-if-changed=./create-chiselstrike-app/template/hello.ts
  cargo:rerun-if-changed=./create-chiselstrike-app/template/package.json
  cargo:rerun-if-changed=./create-chiselstrike-app/template/settings.json
  cargo:rerun-if-changed=./create-chiselstrike-app/template/tsconfig.json
  cargo:rerun-if-changed=./create-chiselstrike-app/tsconfig.json
  cargo:rerun-if-changed=./create-chiselstrike-app/package.json
  v16.14.0

  > create-chiselstrike-app@0.14.0-dev.0 prepare
  > npm run build


  > create-chiselstrike-app@0.14.0-dev.0 build
  > rimraf ./dist && ncc build ./index.ts -o ./dist/

  ncc: Version 0.33.1
  ncc: Compiling file index.js into CJS

  --- stderr
  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:130:10)
      at hashOf (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1890023)
      at ncc (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1894690)
      at runCmd (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:52268)
      at Object.819 (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48838)
      at __webpack_require__ (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59076)
      at /home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59288
      at /home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59349
      at Object.<anonymous> (/home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }
  npm ERR! code 1
  npm ERR! path /home/penberg/src/chiselstrike/chiselstrike/packages/create-chiselstrike-app
  npm ERR! command failed
  npm ERR! command sh -c npm run build

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/penberg/.npm/_logs/2022-10-25T08_45_35_414Z-debug-0.log
  thread 'main' panicked at 'assertion failed: status.unwrap().success()', packages/build.rs:68:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

which is funny because that "digital envelope" error message is supposed to start happening with Node 17, but not with Node 16 that I use...

**Comment by penberg** [comment]
@haaawk Please note that `openssl_legacy_provider_supported()` returns `false`, the print-out comes from `build.rs` trying it out. The real problem here seems to be that we hit that "digital envelope" error for some reason...

**Comment by penberg** [comment]
Ok, I now understand what the issue is.

Fedora 36 ships with OpenSSL 3, which drops some "legacy" policies by default:

https://www.redhat.com/en/blog/legacy-cryptography-fedora-36-and-red-hat-enterprise-linux-9

I am using Node 16 so the workaround you did @haaawk doesn't work.

I worked around the issue by turning on the legacy providers in Fedora:

https://forums.fedoraforum.org/showthread.php?328462-FC35-gt-FC36-OpenSSL-Issues&s=3b662f60a6085c2b30c028867272fccf&p=1859184#post1859184

I assume Node 18 upgrade would have done the trick too, but didn't try that out.

**Comment by haaawk** [comment]
I was using Node 18 when I encountered the problem so I'm not sure using it would solve your problem.
